CREATE DATABASE interact WITH ENCODING='UTF8';
CREATE TABLE CONSUMER_TYPE (
    ID       INT PRIMARY KEY,
    NAME     varchar(100) NOT NULL,
    ASSEMBLY varchar(500) NOT NULL,
    VERSION  varchar(11) NOT NULL
);

CREATE TABLE WORKER_TYPE(
    ID       INT PRIMARY KEY,
    NAME     varchar(100) NOT NULL,
    ASSEMBLY varchar(500) NOT NULL,
    VERSION  varchar(11) NOT NULL
);

CREATE TABLE CONSUMER_SERVER_STATUS(
    ID       INT PRIMARY KEY,
    NAME     varchar(100) NOT NULL
);

CREATE TABLE WORKER_CONFIGURATION(
	ID	INT PRIMARY KEY,
	WORKER_TYPE_ID INT NOT NULL,
	THREADGROUP VARCHAR(200) UNIQUE,
	NAME    VARCHAR(200) NOT NULL,
	JSON    TEXT NOT NULL,
	CONSTRAINT FK_WORKER_CONFIGURATION_WORKER_TYPE_ID FOREIGN KEY (WORKER_TYPE_ID) REFERENCES WORKER_TYPE (ID)
);


CREATE TABLE CLOUD_CONFIGURATION(
	ID	INT PRIMARY KEY,
	NAME    VARCHAR(200) NOT NULL,
	JSON	TEXT NOT NULL
);

CREATE TABLE CLOUD_QUEUE_CONFIGURATION(
	ID	INT PRIMARY KEY,
	CLOUD_CONFIGURATION_ID INT NOT NULL,
	NAME    VARCHAR(200) NOT NULL,
	JSON	TEXT NOT NULL,
	CONSTRAINT FK_CLOUD_QUEUE_CONFIGURATION_CLOUD_CONFIGURATION_ID FOREIGN KEY (CLOUD_CONFIGURATION_ID) REFERENCES CLOUD_CONFIGURATION (ID)

);

CREATE TABLE CLOUD_CONSUMER_CONFIGURATION(
	ID INT PRIMARY KEY,
	CONSUMER_TYPE_ID INT NOT NULL,
	CLOUD_QUEUE_CONFIGURATION_ID INT NOT NULL,
	CONSUMER_SERVER_STATUS_ID INT NOT NULL,
	NAME    VARCHAR(200) NOT NULL,
	JSON    TEXT NOT NULL,
	CONSTRAINT FK_CLOUD_CONSUMER_CONFIGURATION_CLOUD_QUEUE_CONFIGURATION_ID FOREIGN KEY (CLOUD_QUEUE_CONFIGURATION_ID) REFERENCES CLOUD_QUEUE_CONFIGURATION (ID),
	CONSTRAINT FK_CLOUD_CONSUMER_CONFIGURATION_CONSUMER_TYPE_ID FOREIGN KEY (CONSUMER_TYPE_ID) REFERENCES CONSUMER_TYPE (ID),
	CONSTRAINT FK_CLOUD_CONSUMER_CONFIGURATION_CONSUMER_SERVER_STATUS_ID FOREIGN KEY (CONSUMER_SERVER_STATUS_ID) REFERENCES CONSUMER_SERVER_STATUS (ID)
);


CREATE TABLE CLOUD_INSTANCE(
	ID	    INT PRIMARY KEY,
	THREADGROUP VARCHAR(200) UNIQUE ,
	CLOUD_CONSUMER_CONFIGURATION_ID INT NOT NULL,
	WORKER_CONFIGURATION_ID  INT NOT NULL,
	CONSTRAINT FK_CLOUD_INSTANCE_CLOUD_CONSUMER_CONFIGURATION_ID FOREIGN KEY (CLOUD_CONSUMER_CONFIGURATION_ID) REFERENCES CLOUD_CONSUMER_CONFIGURATION (ID),
	CONSTRAINT FK_CLOUD_INSTANCE_WORKER_CONFIGURATION_ID FOREIGN KEY (WORKER_CONFIGURATION_ID) REFERENCES WORKER_CONFIGURATION (ID)
);